using System.Globalization;
using System.Text;

namespace MediaPlayerBridge;

internal sealed class RainmeterWriter
{
    private readonly string _directory = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "MediaPlayerBridge",
        "rainmeter");

    public RainmeterWriter()
    {
        Directory.CreateDirectory(_directory);
    }

    public string CreateCoverPath() =>
        Path.Combine(_directory, $"cover-{DateTimeOffset.UtcNow.Ticks}.jpg");

    public void RemoveOldCovers()
    {
        foreach (var file in Directory.EnumerateFiles(_directory, "cover-*.jpg")
                     .OrderByDescending(File.GetLastWriteTimeUtc)
                     .Skip(3))
        {
            File.Delete(file);
        }
    }

    public async Task WriteAsync(MediaSnapshot snapshot)
    {
        var executable = Environment.ProcessPath?.Replace("\\", "/") ?? "";
        var lines = new[]
        {
            $"; Generated by MediaPlayerBridge at {snapshot.UpdatedAt:O}",
            $"MPB_Executable={Escape(executable)}",
            $"MPB_Source={Escape(snapshot.Source)}",
            $"MPB_Title={Escape(snapshot.Title)}",
            $"MPB_Artist={Escape(snapshot.Artist)}",
            $"MPB_Album={Escape(snapshot.Album)}",
            $"MPB_Genre={Escape(snapshot.Genre)}",
            $"MPB_Status={Escape(snapshot.PlaybackStatus)}",
            $"MPB_StateIcon={snapshot.StateIcon}",
            $"MPB_Position={Escape(snapshot.PositionText)}",
            $"MPB_Duration={Escape(snapshot.DurationText)}",
            $"MPB_PositionSeconds={snapshot.PositionSeconds.ToString(CultureInfo.InvariantCulture)}",
            $"MPB_DurationSeconds={Math.Max(snapshot.DurationSeconds, 1).ToString(CultureInfo.InvariantCulture)}",
            $"MPB_CoverPath={snapshot.CoverPath.Replace("\\", "/")}",
            $"MPB_IsPlaying={(snapshot.PlaybackStatus == "Playing" ? "1" : "0")}",
            $"MPB_CanNext={(snapshot.CanNext ? "1" : "0")}",
            $"MPB_CanPrevious={(snapshot.CanPrevious ? "1" : "0")}"
        };

        var target = Path.Combine(_directory, "MediaPlayerBridge.inc");
        var temporary = target + ".tmp";
        await File.WriteAllLinesAsync(temporary, lines, Encoding.UTF8);
        File.Move(temporary, target, true);
    }

    private static string Escape(string value) =>
        value.Replace("\r", " ").Replace("\n", " ").Replace("=", "-").Trim();
}
